server:
  port: 8080
spring:
  application:
    name: monolithic
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MonolithicEcommerce
    username: admin
    password: 123456